spring:
  logging:
    level:
      org.springframework.web: DEBUG
      reactor.netty: DEBUG
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.nyt.technews: DEBUG
    reactor.netty.http.client: WARN

nyt:
  api:
    base-url: https://rss.nytimes.com
    rss-path: /services/xml/rss/nyt/Technology.xml
    timeouts:
      connect: 1000
      read: 1000
      write: 1000
    connection-pool:
      max-connections: 100
      acquire-timeout: 5000
      idle-timeout: 30000
  retry:
    max-attempts: 0
    backoff:
      initial-interval: 0ms
      max-interval: 0ms